### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by afkvido** [udu3324/Typsnd#44]
so looking at https://github.com/udu3324/Typsnd/blob/master/LICENCE.md that means its ok to make a carbon copy of Typsend on Kotlin (at https://github.com/afkvido/TSR), as long as i include a copyright notice for you.

are you ok with that or should i not make TSR at all?

**Comment by afkvido** [comment]
*not all of it is a carbon copy, more of a similar replica, but the client code is copied

**Comment by udu3324** [comment]
Yeah you can create Typsnd in Kotlin
It would also be nice if you could link back to the original project :>

**Comment by afkvido** [comment]
Bet

**Comment by afkvido** [comment]
>  It would also be nice if you could link back to the original project :>

https://github.com/afkvido/TSR/commit/dcfd3487550d08ae29fdfd2fdb9caf0af74d1f18

**Comment by afkvido** [comment]
Oh also https://github.com/afkvido/TSR/commit/d12dcb85f9f08564e46344e508fe559b6409503c
