### ISSUE TITLE
Username in bottom right corner is not properly filtered

### ISSUE THREAD

**Issue by PatheticMustan** [udu3324/Typsnd#46]
**Describe the bug**
See title

**To Reproduce**
1. Log in with a username like `<b>test</b>`
2. Look towards the bottom right corner

**Screenshots**
![image](https://user-images.githubusercontent.com/35382971/197400993-7ec23ed2-6cff-415b-8d90-9e0e2700cc91.png)

**Additional context**
A simple one line fix, just add filtering here
https://github.com/udu3324/Typsnd/blob/1a55ec9d380c44edf74376f63b8158b204734427/public/js/chat.js#L65

**Comment by afkvido** [comment]
@PatheticMustan This is only possible if you're admin, as usually you're username has to go through DOMpurify otherwise.

**Comment by PatheticMustan** [comment]
no.... if you just look at the line I linked, it doesn't put anything through DOMpurify
I haven't looked at if the admin or other users can view this, but I would guess not.
it's just a minor issue, but i thought i should point it out

**Comment by afkvido** [comment]
Na, because it's in chat.js. If the client managed to get to chat.js, (got past join.js), it means that the username has already been filtered by the server.

**Comment by afkvido** [comment]
Wait hol up i dont think DOMpurify sanitizes usernames @udu3324 take a look this issue is very important bc anti xss could be broken by this

**Comment by udu3324** [comment]
Thank you for finding a bug! DOMpurify was scanning for XSS sucessfully, but not for safe tags/elements like bold and underline

Commit 20f78071d607cbca7650fc144cce58bbbee041d9 fixes this & allows users with < and > to be mentioned

Usernames are XSS scanned even if they're an admin btw
